# ============================================================================
# GolangCI-Lint 配置
# ----------------------------------------------------------------------------
# 目标：
#   1) 在 CI 中提供稳定、可重复的静态检查结果（不依赖网络波动/隐式依赖变更）
#   2) 只启用“高信噪比”的规则集，避免噪音过大导致团队忽略告警
#   3) 代码风格（gofmt/goimports）与潜在缺陷（staticcheck/govet/errcheck）双管齐下
#
# 使用方式（建议）：
#   - CI：golangci-lint run --timeout=5m
#   - 本地（修复格式类问题）：golangci-lint run --fix （谨慎，可能改 import/格式）
#
# 注意：
#   - 本配置采用“disable-all + allowlist enable”的白名单策略，
#     防止 golangci-lint 升级后默认启用新 linter 导致 CI 突然爆红。
# ============================================================================

run:
  # 生产级建议：为 lint 设置硬超时，避免某些分析器在大仓库/复杂泛型下耗时过长
  # 超时会让 CI 失败，从而强制问题被可见化，而不是“卡住不结束”。
  timeout: 5m

  # 生产级建议：只读模式，禁止 CI 自动修改 go.mod / go.sum。
  # 好处：
  #   - 保证构建/检查的可重复性（依赖必须在代码中显式声明）
  #   - 防止 CI 环境隐式运行时把依赖文件改了却没人提交
  # 若依赖不完整，应在本地运行 go mod tidy / go mod download 后提交变更。
  modules-download-mode: readonly

linters:
  # 白名单策略：先禁用全部，再显式启用需要的 linter（避免升级带来的行为变化）
  disable-all: true
  enable:
    # ------------------------------------------------------------------------
    # 缺陷/可靠性相关（高价值）
    # ------------------------------------------------------------------------

    # 检查被忽略的 error 返回值：避免“调用失败但无人知晓”的隐患
    - errcheck

    # Go 官方 vet：捕获格式化字符串/无效 build tag/锁误用等典型问题
    - govet

    # staticcheck：强静态分析（空指针风险、无效代码、性能/正确性问题等）
    # 通常是“生产事故预防器”之一
    - staticcheck

    # typecheck：类型检查（即使你没显式 go build，也能把编译级错误暴露出来）
    - typecheck

    # ineffassign：发现“赋值了但从未使用”的无效赋值（多见于逻辑遗漏/重构残留）
    - ineffassign

    # unused：未使用的变量/常量/函数等（保持代码整洁，减少误导性死代码）
    - unused

    # gosimple：提示可简化写法（提升可读性、减少冗余）
    - gosimple

    # ------------------------------------------------------------------------
    # 代码风格/一致性相关（生产协作刚需）
    # ------------------------------------------------------------------------

    # gofmt：强制统一格式（避免 PR 因格式争论、减少 diff 噪音）
    - gofmt

    # goimports：自动整理 import（删除未用、补齐缺失、分组排序）
    # 生产建议：与 gofmt 一起作为“风格门禁”，保障多人协作一致性
    - goimports

linters-settings:
  goimports:
    # 本地包前缀：告诉 goimports 哪些属于“项目内部包”，便于 import 分组：
    #   1) 标准库
    #   2) 第三方库
    #   3) 本项目内部包（以该前缀开头）
    #
    # 你这里是 personal_assistant（比如 personal_assistant/pkg/...）
    # 如果你的 module path 实际是 github.com/xxx/personal_assistant，
    # 也可以填更精确的 module path 前缀以匹配实际 import。
    local-prefixes: personal_assistant

issues:
  # 是否使用 golangci-lint 默认的排除规则：
  # false = 使用默认 exclude（通常是为了过滤一些已知噪音/误报场景）
  # 生产建议：保持默认，减少不必要的噪音
  exclude-use-default: false

  # 每个 linter 最多报告多少条问题：
  # 0 = 不限制（让 CI 把问题完整暴露，而不是截断）
  # 生产建议：小团队/中等规模仓库可用 0；
  # 若历史遗留问题很多，可暂时设置一个上限并逐步清理。
  max-issues-per-linter: 0

  # 同一类问题最多报告多少条：
  # 0 = 不限制（完整输出，便于一次性修完同类问题）
  max-same-issues: 0